### ISSUE TITLE
Ajax failure error

### ISSUE THREAD

**Issue by Hoao** [paps/adopte-server#2]
Hello,

je n'arrive pas à faire fonctionner le script, j'obtiens cette erreur dans Firefox :
`>>> Ajax failure: %j Object { jqXhr: Object, textStatus: "error", err: "" } aum.user.js:420:1`

Le serveur se lance sans erreur, il doit y avoir un problème au niveau de la config,
à quoi correspondent exactement  config.secrets.session, auth et key ?

Merci

**Comment by jeremv42** [comment]
Bonjour,

config.secrets.session correspond à une clé aléatoire pour initialiser le générateur de session.
config.adopte.auth doit contenir votre login/mot de passe d'adopte (en base64, voir https://fr.wikipedia.org/wiki/Authentification_HTTP#M.C3.A9thode_.C2.AB_Basic_.C2.BB), il permet de se connecter aux API d'adopte.
config.adopte.key est la clé utilisé entre le serveur et le script greasemonkey coté client, elles doivent correspondre.
